# Generated by Django 5.1.7 on 2025-04-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_created_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id']},
        ),
    ]
